/**
 * Action types constants use to define an action type.
 * 
 * @author Koh Tong Liang
 * @version 1
 * @since 30/10/2020
 */

/**
 * Action types for Home Actions
 */
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const TOGGLE_TRAFFIC_IMAGES_VIEW = 'TOGGLE_TRAFFIC_IMAGES_VIEW';
export const TOGGLE_ROUTE_PLANNER = 'TOGGLE_ROUTE_PLANNER';
export const TOGGLE_MAP_PICKER = 'TOGGLE_MAP_PICKER';
export const GET_USER_LOCATION_SUCCEEDED = 'GET_USER_LOCATION_SUCCEEDED';
export const HISTORY_VIEW = 'HISTORY_VIEW';
export const BOOKMARK_VIEW = 'BOOKMARK_VIEW';
export const RETURN_MAP_PICKER_RESULT = 'RETURN_MAP_PICKER_RESULT';
export const SET_FAILURE_MESSAGE = 'SET_FAILURE_MESSAGE';

/**
 * Action types for Map Actions
 */
export const GET_TRAFFIC_IMAGES = 'GET_TRAFFIC_IMAGES';
export const GET_TRAFFIC_IMAGES_SUCCEEDED = 'GET_TRAFFIC_IMAGES_SUCCEEDED';
export const GET_ERP_DATA = 'GET_ERP_DATA';
export const GET_ERP_DATA_SUCCEEDED = 'GET_ERP_DATA_SUCCEEDED';
export const UPDATE_CAMERA_MARKERS = 'UPDATE_CAMERA_MARKERS';
export const UPDATE_LINE_STRING = 'UPDATE_LINE_STRING';
export const UPDATE_NEXT_CAMERA = 'UPDATE_NEXT_CAMERA';
export const SET_USER_MARKER = 'SET_USER_MARKER';
export const SET_PINNED_CAMERA_MARKERS = 'SET_PINNED_CAMERA_MARKERS';
export const SET_ERP_MARKERS = 'SET_ERP_MARKERS';
export const SET_STEP_MARKERS = 'SET_STEP_MARKERS';
export const SET_MAP = 'SET_MAP';

/**
 * Action types for Navigation/Route Planner
 */
export const SEARCH_START_LOCATION = 'SEARCH_START_LOCATION';
export const SEARCH_START_LOCATION_SUCCEEDED = 'SEARCH_START_LOCATION_SUCCEEDED';
export const SEARCH_END_LOCATION = 'SEARCH_END_LOCATION';
export const SEARCH_END_LOCATION_SUCCEEDED = 'SEARCH_END_LOCATION_SUCCEEDED';
export const PROCESS_START_LOCATION = 'PROCESS_START_LOCATION';
export const PROCESS_END_LOCATION = 'PROCESS_END_LOCATION';
export const PLAN_ROUTE = 'PLAN_ROUTE';
export const PLAN_ROUTE_SUCCEEDED = 'PLAN_ROUTE_SUCCEEDED';
export const TRIP_SUMMARY = 'TRIP_SUMMARY';
export const SAVE_TRIP = 'SAVE_TRIP';
export const MAP_MATCHING = 'MAP_MATCHING';
export const MAP_MATCHING_SUCCEEDED = 'MAP_MATCHING_SUCCEEDED';
export const CANCEL_ROUTE = 'CANCEL_ROUTE';
export const REROUTE = 'REROUTE';
export const REROUTE_SUCCEEDED = 'REROUTE';
export const UPDATE_STEPS = 'UPDATE_STEPS';
export const FILTER_ROUTE_ERP = 'FILTER_ROUTE_ERP';
export const SAVE_ROUTE_NAME = 'SAVE_ROUTE_NAME';
export const RUN_HISTORY = 'RUN_HISTORY';
export const DELETE_HISTORY = 'DELETE_HISTORY';
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK';
export const GET_NAME_OF_PLACE = 'GET_NAME_OF_PLACE';
export const SET_START_LOCATION_SEARCH = 'SET_START_LOCATION_SEARCH';
export const SET_END_LOCATION_SEARCH = 'SET_END_LOCATION_SEARCH';

/**
 * Action types for Firebase
 */
export const SIGN_IN = 'SIGN_UP';
export const SIGN_UP = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const SAVE_HISTORY = 'SAVE_HISTORY';
export const SAVE_HISTORY_SUCCESS = 'SAVE_HISTORY_SUCCESS';
export const LOAD_HISTORY = 'LOAD_HISTORY';
export const LOAD_HISTORY_SUCCESS = 'LOAD_HISTORY_SUCCESS';

/**
 * Action types defined for demo and debugging purposes.
 */
export const OVERRIDE_USER_LOCATION = 'OVERRIDE_USER_LOCATION';